// sogang-icpc-team.github.io-react/src/common/ui/award-badge/award-badge.tsx
import styled from "styled-components";

export type TAwardBadgeVariant = "gold" | "silver" | "bronze";

const _AwardBadge = ({
  className,
}: {
  className?: string;
  variant: TAwardBadgeVariant;
}) => {
  return <span className={className}>⬤</span>;
};

export const AwardBadge = styled(_AwardBadge)`
  vertical-align: super;
  font-size: 13px;
  color: ${({ variant }) => {
    switch (variant) {
      case "gold":
        return "gold";
      case "silver":
        return "silver";
      case "bronze":
        return "#CD7F32";
    }
  }};
`;

// src/routes/clean-water-cup/AwardBadge.svelte
<script>
  export let variant;
  const variantColorMap = {
    gold: "gold",
    silver: "silver",
    bronze: "#CD7F32",
  };
  $: cssVariables = `--variant: ${variantColorMap[variant]};`;
</script>

<span class="award-badge" style={cssVariables}>⬤</span>

<style lang="scss">
  .award-badge {
    vertical-align: super;
    font-size: 13px;
    color: var(--variant);
  }
</style>
